services:

  postgres:
    image: postgres:17.5
    container_name: prod_support_postgres
    ports:
      - "5000:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: prod_support_adminer
    restart: always
    ports:
      - 8888:8080


  
volumes:
  postgres_data:


